### PR TITLE
Add navbar and make page mobile-friendly

### PR DESCRIPTION
**Pull request by TsarN**
The title describes this PR pretty well.

### CODE REVIEW

**Comment by DarthGandalf** [comment]
How did you test this? It doesn't look too good on mobile for me: 
image

**Comment by TsarN** [comment]
> How did you test this? It doesn't look too good on mobile for me:

Firefox's mobile emulation mode. It definitely does look good on these.
image

**Comment by DarthGandalf** [comment]
Me too. But I used the responsive mode with width 320 instead of selecting on of those devices

**Comment by TsarN** [comment]
How about now?

**Pull request merged**
